##PS: sim, é nome de Cachaça!
#
##
##Arquivo de Testes Loucos, desconsidere porra!
##
#
#
#table_names = ['users','groups','permissions','group_users','group_permissions']
#tables_atrrs = [#<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0xb6c77cdc @limit=nil, @null=false, @sql_type="integer", @name="id", @type=:integer, @scale=nil, @precision=nil, @primary=nil, @default=nil>, #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0xb6c733a8 @limit=40, @null=true, @sql_type="character varying(40)", @name="login", @type=:string, @scale=nil, @precision=nil, @primary=nil, @default=nil>, #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0xb6c73330 @limit=100, @null=true, @sql_type="character varying(100)", @name="email", @type=:string, @scale=nil, @precision=nil, @primary=nil, @default=nil>, #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0xb6c73240 @limit=100, @null=true, @sql_type="character varying(100)", @name="nome", @type=:string, @scale=nil, @precision=nil, @primary=nil, @default=nil>, #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0xb6c73178 @limit=40, @null=true, @sql_type="character varying(40)", @name="crypted_password", @type=:string, @scale=nil, @precision=nil, @primary=nil, @default=nil>, #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0xb6c730b0 @limit=40, @null=true, @sql_type="character varying(40)", @name="salt", @type=:string, @scale=nil, @precision=nil, @primary=nil, @default=nil>, #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0xb6c72fe8 @limit=255, @null=true, @sql_type="character varying(255)", @name="remember_token", @type=:string, @scale=nil, @precision=nil, @primary=nil, @default=nil>, #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0xb6c72f20 @limit=nil, @null=true, @sql_type="timestamp without time zone", @name="remember_token_expires_at", @type=:datetime, @scale=nil, @precision=nil, @primary=nil, @default=nil>, #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0xb6c72e58 @limit=nil, @null=true, @sql_type="boolean", @name="active", @type=:boolean, @scale=nil, @precision=nil, @primary=nil, @default=true>, #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0xb6c72db8 @limit=nil, @null=true, @sql_type="timestamp without time zone", @name="created_at", @type=:datetime, @scale=nil, @precision=nil, @primary=nil, @default=nil>, #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0xb6c72d54 @limit=nil, @null=true, @sql_type="timestamp without time zone", @name="updated_at", @type=:datetime, @scale=nil, @precision=nil, @primary=nil, @default=nil>]
#
#
#
#
#
#
#
#
#
#

puts "lololol"
@file = File.new('conf.yml','w')
#@file.puts "aaaaaaaa"
@file.puts "--- \n- !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn \n  default: \n  limit: \n  name: id\n  \"null\": false\n  precision: \n  primary: \n  scale: \n  sql_type: integer\n  type: :integer\n- !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn \n  default: \n  limit: 40\n  name: login\n  \"null\": true\n  precision: \n  primary: \n  scale: \n  sql_type: character varying(40)\n  type: :string\n- !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn \n  default: \n  limit: 100\n  name: email\n  \"null\": true\n  precision: \n  primary: \n  scale: \n  sql_type: character varying(100)\n  type: :string\n- !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn \n  default: \n  limit: 100\n  name: nome\n  \"null\": true\n  precision: \n  primary: \n  scale: \n  sql_type: character varying(100)\n  type: :string\n- !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn \n  default: \n  limit: 40\n  name: crypted_password\n  \"null\": true\n  precision: \n  primary: \n  scale: \n  sql_type: character varying(40)\n  type: :string\n- !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn \n  default: \n  limit: 40\n  name: salt\n  \"null\": true\n  precision: \n  primary: \n  scale: \n  sql_type: character varying(40)\n  type: :string\n- !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn \n  default: \n  limit: 255\n  name: remember_token\n  \"null\": true\n  precision: \n  primary: \n  scale: \n  sql_type: character varying(255)\n  type: :string\n- !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn \n  default: \n  limit: \n  name: remember_token_expires_at\n  \"null\": true\n  precision: \n  primary: \n  scale: \n  sql_type: timestamp without time zone\n  type: :datetime\n- !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn \n  default: true\n  limit: \n  name: active\n  \"null\": true\n  precision: \n  primary: \n  scale: \n  sql_type: boolean\n  type: :boolean\n- !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn \n  default: \n  limit: \n  name: created_at\n  \"null\": true\n  precision: \n  primary: \n  scale: \n  sql_type: timestamp without time zone\n  type: :datetime\n- !ruby/object:ActiveRecord::ConnectionAdapters::PostgreSQLColumn \n  default: \n  limit: \n  name: updated_at\n  \"null\": true\n  precision: \n  primary: \n  scale: \n  sql_type: timestamp without time zone\n  type: :datetime\n"

